var hierarchy =
[
    [ "Colors", "class_colors.html", null ],
    [ "CountryCodes", "struct_country_codes.html", null ],
    [ "Data", "class_data.html", null ],
    [ "DatabaseManager", "class_database_manager.html", null ],
    [ "Colors.Entry", "class_colors_1_1_entry.html", null ],
    [ "Message", "class_message.html", null ],
    [ "MonoBehaviour", null, [
      [ "ARBrush", "class_a_r_brush.html", null ],
      [ "ARGuide", "class_a_r_guide.html", null ],
      [ "ARMarker", "class_a_r_marker.html", null ],
      [ "ARPointer", "class_a_r_pointer.html", null ],
      [ "ARText", "class_a_r_text.html", null ],
      [ "ARToolManager", "class_a_r_tool_manager.html", null ],
      [ "AndroidUtils", "class_android_utils.html", null ],
      [ "AppEntryPoint", "class_app_entry_point.html", null ],
      [ "AudioManager", "class_audio_manager.html", null ],
      [ "AudioVisualizerController", "class_audio_visualizer_controller.html", null ],
      [ "BackButtonController", "class_back_button_controller.html", null ],
      [ "ClientManager", "class_client_manager.html", null ],
      [ "ContactsController", "class_contacts_controller.html", null ],
      [ "DynamicLinksInit", "class_dynamic_links_init.html", null ],
      [ "FirebaseInit", "class_firebase_init.html", null ],
      [ "LookAtCamera", "class_look_at_camera.html", null ],
      [ "MainUIController", "class_main_u_i_controller.html", null ],
      [ "MicrophoneListener", "class_microphone_listener.html", null ],
      [ "MyInputManager", "class_my_input_manager.html", null ],
      [ "OneSignalInit", "class_one_signal_init.html", null ],
      [ "PeerConnectionManager", "class_peer_connection_manager.html", null ],
      [ "RecorderManager", "class_recorder_manager.html", null ],
      [ "RegisterNameUIController", "class_register_name_u_i_controller.html", null ],
      [ "RegisterPhoneUIController", "class_register_phone_u_i_controller.html", null ],
      [ "RoomsController", "class_rooms_controller.html", null ],
      [ "ToolbarUIController", "class_toolbar_u_i_controller.html", null ],
      [ "TopbarUIController", "class_topbar_u_i_controller.html", null ],
      [ "VideoManager", "class_video_manager.html", null ],
      [ "WindowRes", "class_window_res.html", null ]
    ] ],
    [ "MySceneManager", "class_my_scene_manager.html", null ],
    [ "RoomManager", "class_room_manager.html", null ],
    [ "SharingManager", "class_sharing_manager.html", null ],
    [ "User", "class_user.html", null ],
    [ "UserManager", "class_user_manager.html", null ]
];