var hierarchy =
[
    [ "Colors", "d9/d36/class_colors.html", null ],
    [ "CountryCodes", "d4/dbc/struct_country_codes.html", null ],
    [ "Data", "dc/d07/class_data.html", null ],
    [ "DatabaseManager", "d5/dd7/class_database_manager.html", null ],
    [ "Colors.Entry", "d7/d0e/class_colors_1_1_entry.html", null ],
    [ "Message", "d4/d7f/class_message.html", null ],
    [ "MonoBehaviour", null, [
      [ "ARBrush", "da/d70/class_a_r_brush.html", null ],
      [ "ARGuide", "d4/d25/class_a_r_guide.html", null ],
      [ "ARMarker", "d6/d6a/class_a_r_marker.html", null ],
      [ "ARPointer", "d1/d71/class_a_r_pointer.html", null ],
      [ "ARText", "d0/dac/class_a_r_text.html", null ],
      [ "ARToolManager", "d7/d5d/class_a_r_tool_manager.html", null ],
      [ "AppEntryPoint", "d0/dda/class_app_entry_point.html", null ],
      [ "AudioManager", "d7/d31/class_audio_manager.html", null ],
      [ "AudioVisualizerController", "d6/d16/class_audio_visualizer_controller.html", null ],
      [ "BackButtonController", "d9/de1/class_back_button_controller.html", null ],
      [ "ClientManager", "db/d71/class_client_manager.html", null ],
      [ "ContactsController", "db/d20/class_contacts_controller.html", null ],
      [ "DynamicLinksInit", "d8/d78/class_dynamic_links_init.html", null ],
      [ "FirebaseInit", "d9/da2/class_firebase_init.html", null ],
      [ "LookAtCamera", "d1/d57/class_look_at_camera.html", null ],
      [ "MainUIController", "dd/d3b/class_main_u_i_controller.html", null ],
      [ "MyInputManager", "dc/d59/class_my_input_manager.html", null ],
      [ "OneSignalInit", "d2/d84/class_one_signal_init.html", null ],
      [ "PeerConnectionManager", "d2/d48/class_peer_connection_manager.html", null ],
      [ "RecorderManager", "dc/da3/class_recorder_manager.html", null ],
      [ "RegisterNameUIController", "d8/d7d/class_register_name_u_i_controller.html", null ],
      [ "RegisterPhoneUIController", "dd/ddc/class_register_phone_u_i_controller.html", null ],
      [ "RoomsController", "d9/da4/class_rooms_controller.html", null ],
      [ "ToolbarUIController", "d0/d5f/class_toolbar_u_i_controller.html", null ],
      [ "TopbarUIController", "d7/d42/class_topbar_u_i_controller.html", null ],
      [ "VideoManager", "d2/dba/class_video_manager.html", null ],
      [ "WindowRes", "dc/df2/class_window_res.html", null ]
    ] ],
    [ "MySceneManager", "d3/dda/class_my_scene_manager.html", null ],
    [ "RoomManager", "d2/d43/class_room_manager.html", null ],
    [ "SharingManager", "dd/dcc/class_sharing_manager.html", null ],
    [ "User", "d7/d23/class_user.html", null ],
    [ "UserManager", "d1/da2/class_user_manager.html", null ]
];